Artemis/urls.py
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('', include('apps.index.urls')),
    path('', include('pwa.urls')),
    path('djangoadmin/', admin.site.urls),
    path('usuario/', include('apps.usuario.urls')),
    path('reclamo/', include('apps.reclamo.urls')),
    path('resp_predefinida/', include('apps.resp_predefinida.urls')),
    path('pqs/', include('apps.pqs.urls')),
    path('datosexternos/', include('apps.datos_externos.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reclamo/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include

urlpatterns = [
    path('lista/todos/', views.g_listareclamos.as_view(), name='g_listareclamos'),
    path('lista/finalizados/', views.g_reclamosfinalizados.as_view(), name='g_reclamosfinalizados'),
    path('lista/proximovencimiento/', views.reclamosporvencer.as_view(), name='reclamosporvencer'),
    path('registrar/', views.cli_crearReclamo.as_view(), name='cli_crearReclamo'),
    path('atc_registrar/', views.atc_crearReclamo.as_view(), name='atc_crearReclamo'),
    path('consultar/<pk>/', views.gt_consultarReclamo.as_view(), name='gt_consultarReclamo'),
    path('atender/<pk>/', views.atenderReclamo.as_view(), name='atenderReclamo'),
    path('categoria/crear/', views.crearcatreclamo.as_view(), name='crearcatreclamo'),
    path('categoria/lista/', views.listacatreclamo.as_view(), name='listacatreclamo'),
    path('categoria/consulta/<pk>/', views.consultarcatreclamo.as_view(), name='consultarcatreclamo'),
    path('categoria/modificar/<pk>/', views.modificarcatreclamo.as_view(), name='modificarcatreclamo'),
    path('finalizados/lista/', views.cli_reclamosfinalizados.as_view(), name='cli_reclamosfinalizados'),
    path('satisfaccion/encuesta/<pk>/', views.encuesta_cliente.as_view(), name='encuesta_cliente'),
    path('cliente/consultar/<pk>/', views.cli_consultarReclamo.as_view(), name='cli_consultarReclamo'),
]

apps/reclamo/models.py
from django.db import models
from datetime import datetime, timedelta
from apps.datos_externos.models import DetalleContrato
from apps.usuario.models import User
from apps.usuario.models import EficienciaGestor
from django.db.models.signals import post_save
from django.dispatch import receiver
from notifications.signals import notify

# Create your models here.
class Categoria(models.Model):

    def cod_categoria():
        categoria = Categoria
        ult_categoria = categoria.objects.all().count()

        if not ult_categoria:
            return 'CTR-0000'

        nro_categoria = int(ult_categoria)
        nvo_codcategoria = 'CTR-' + str(nro_categoria).zfill(4) 

        return nvo_codcategoria

    codCategoria = models.CharField(max_length=8, default=cod_categoria, primary_key=True)
    nombre = models.CharField(max_length=40)
    descripcion = models.CharField(max_length=120)
    ESTATUS = ( 
        ('A','Activo'),
        ('I','Inactivo'),
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')

    def __str__(self):
        return self.nombre

class Reclamo(models.Model):

    def cod_reclamo():
        reclamo = Reclamo
        ult_reclamo = reclamo.objects.all().count()

        if not ult_reclamo:
            return 'REC-0000'

        nro_reclamo = int(ult_reclamo)
        nvo_codreclamo = 'REC-' + str(nro_reclamo).zfill(4) 

        return nvo_codreclamo

    codReclamo = models.CharField(max_length=8, default=cod_reclamo, primary_key=True)
    codDetContrato = models.ForeignKey(DetalleContrato, on_delete=models.CASCADE)
    codCategoria = models.ForeignKey(Categoria, on_delete=models.CASCADE,blank=True, null=True)
    nombreUsuario = models.ForeignKey(User,on_delete=models.CASCADE, related_name='autor')
    descripcion = models.CharField(max_length=500)
    fechaRegistro = models.DateTimeField(default=datetime.now)
    fechaEstimada = models.DateField(blank=True, null=True)
    fechaFinalizada = models.DateTimeField(blank=True, null=True)
    responsableReclamo = models.ManyToManyField(User, blank=True)
    valoracion = models.CharField(max_length=1,blank=True, null=True)
    ESTATUS = ( 
        ('P','Pendiente'),
        ('R','En proceso'),
        ('F','Finalizado'),
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='P')

    def __str__(self):
        return self.codReclamo + ' / ' + self.nombreUsuario.nombreUsuario +' / ' + self.nombreUsuario.idCliente.nombre + ' / ' + self.descripcion[:20] + '...'

class HistoricoReclamo(models.Model):
    reclamo = models.ForeignKey(Reclamo, on_delete=models.CASCADE,blank=True, null=True)
    fecha = models.DateField(auto_now = True, blank=True, null=True)
    detalle = models.CharField(max_length = 200)
    TIPO = (
        ('A','Actualizacion'),
        ('C','Comentario'),
    )
    tipo = models.CharField(max_length=1,choices=TIPO, default='A')
    usuarioEncargado = models.CharField(max_length = 20)

    def notificar(self, descripcion):
        notify.send(sender=self, recipient=self.reclamo.nombreUsuario, verb='n', description=descripcion)

    def __str__(self):
        return self.reclamo.codReclamo

class Configuracion(models.Model):
    nombre = models.CharField(max_length=10)
    valor = models.IntegerField()

@receiver(post_save, sender=Reclamo)
def asignar_reclamo(sender, instance, **kwargs):
    if instance.responsableReclamo.all().count() == 0:
        minimo = Configuracion.objects.get(id=1).valor
        maximo = Configuracion.objects.get(id=2).valor
        gestores = User.objects.filter(codTipoUser = "grec", estatus = "A", is_active = True)
        gestores_posibles = list()
        gestores_max = list() 
        correspondencia = list()
        correspondencia_max = list()

        for gestor in gestores:
            eg = EficienciaGestor.objects.get(nombreUsuario = gestor)
            cantidad = Reclamo.objects.filter(responsableReclamo=gestor).exclude(estatus="F").count()
            
            if cantidad < minimo:
                instance.responsableReclamo.add(gestor)
                dias_tarda = round((cantidad / eg.eficiencia) + 0.5) + 1
                hoy = datetime.now()
                while dias_tarda > 0:
                    hoy += timedelta(days=1)
                    dia_semana = hoy.weekday()
                    if dia_semana >= 5:
                        continue
                    dias_tarda -= 1
                instance.fechaEstimada = hoy
                instance.save()
                return
            elif cantidad < maximo:
                gestores_posibles.append(gestor)
                correspondencia.append(cantidad / eg.eficiencia)
            else:
                gestores_max.append(gestor)
                correspondencia_max.append(cantidad / eg.eficiencia)

        if len(correspondencia) != 0:
            indice = correspondencia.index(min(correspondencia))
            instance.responsableReclamo.add(gestores_posibles[indice])
            cantidad = Reclamo.objects.filter(responsableReclamo=gestores_posibles[indice]).exclude(estatus="F").count()
            eg = EficienciaGestor.objects.get(nombreUsuario=gestores_posibles[indice])
            dias_tarda = round((cantidad / eg.eficiencia) + 0.5) + 2
            hoy = datetime.now()
            while dias_tarda > 0:
                hoy += timedelta(days=1)
                dia_semana = hoy.weekday()
                if dia_semana >= 5:
                    continue
                dias_tarda -= 1
            instance.fechaEstimada = hoy
            instance.save()
        elif len(correspondencia_max) != 0:
            indice = correspondencia_max.index(min(correspondencia_max))
            instance.responsableReclamo.add(gestores_max[indice])
            cantidad = Reclamo.objects.filter(responsableReclamo=gestores_max[indice]).exclude(estatus="F").count()
            eg = EficienciaGestor.objects.get(nombreUsuario=gestores_max[indice])
            dias_tarda = round((cantidad / eg.eficiencia) + 0.5) + 2
            hoy = datetime.now()
            while dias_tarda > 0:
                hoy += timedelta(days=1)
                dia_semana = hoy.weekday()
                if dia_semana >= 5:
                    continue
                dias_tarda -= 1
            instance.fechaEstimada = hoy
            instance.save()

apps/reclamo/forms.py
from django import forms 
from .models import Categoria, Reclamo

class IncluirCategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria

        fields = [
            'nombre',
            'descripcion',
        ]

        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ingresar nombre de categoría aquí.'}),
            'descripcion' : forms.Textarea(attrs={'class':'form-control','cols':6,'rows':8,'placeholder':'Ingresar descripción de categoría aquí.'}),
        }

class ConsultarCategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria

        fields = [
            'codCategoria',
            'nombre',
            'descripcion',
            'estatus',
        ]

        widgets = {
            'codCategoria' : forms.TextInput(attrs={'class':'form-control','readonly':''}),
            'nombre' : forms.TextInput(attrs={'class':'form-control','readonly':''}),
            'descripcion' : forms.Textarea(attrs={'class':'form-control','cols':6,'rows':8,'readonly':''}),
            'estatus' : forms.TextInput(attrs={'class':'form-control','id':'estatus','type':'hidden'}),
        }

class ActualizarCategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria

        fields = [
            'codCategoria',
            'nombre',
            'descripcion',
        ]

        widgets = {
            'codCategoria' : forms.TextInput(attrs={'class':'form-control', 'readonly':''}),
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'descripcion' : forms.Textarea(attrs={'class':'form-control','cols':6,'rows':8}),
        }

class IncluirReclamo(forms.ModelForm):

    class Meta:
        model = Reclamo

        fields = [
            'nombreUsuario',
            'descripcion',
            'codDetContrato',
            'codCategoria',
        ]

        widgets = {
            'nombreUsuario' : forms.TextInput(attrs={'id':'nombreusuario', 'type':'hidden'}),
            'descripcion' : forms.Textarea(attrs={'class':'form-control','cols':6,'rows':12,'placeholder':'Por favor escriba su reclamo aquí...','required':''}),
        }

class ConsultarReclamo(forms.ModelForm):
    
    class Meta:
        model = Reclamo

        fields = [
            'estatus',
        ]
        
        widgets = {
            'estatus' :  forms.TextInput(attrs={'class':'form-control','readonly':''}),
        }

class AtenderReclamo(forms.ModelForm):

    class Meta:
        model = Reclamo

        fields = [
            'fechaEstimada',
            'codCategoria',
            'estatus',
            'fechaFinalizada',
        ]

        widgets = {
            'fechaEstimada' : forms.DateInput(attrs={'class':'form-control'}),
            'estatus' : forms.Select(attrs={'class':'form-control','id':'estatus'}),
            'codCategoria' : forms.Select(attrs={'class':'form-control'}),
            'fechaFinalizada' : forms.DateTimeInput(attrs={'class':'form-control'}),
        }

class EncuestaCliente(forms.ModelForm):

    class Meta:
        model = Reclamo

        fields = [
            'valoracion',
        ]

templates/reclamo/atc_crearReclamo.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %}Crear Reclamo | Artemis {% endblock %}

<!--CREAR RECLAMO PARA USUARIOS: ATENCION AL CLIENTE -->

{% block content %}

<div class="card">
    <div class="header">
        <h2>
            Registrar Reclamo <small style="color:black; text-align:justify;">El reclamo es una declaración por el
                incumplimiento de un servicio que ha sido contratado, ocasionado por la deficiente prestación o
                suspensión injustificada del servicio.</small>
        </h2>
    </div>
    <div class="body">
        <form method="POST" id="formulario">
            {% csrf_token %}
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="header" style="background-color:#858392">
                                <h2>
                                    Datos del cliente:
                                </h2>
                            </div>
                        </div>
                        {{ form.nombreUsuario }}
                        <div class=" col-md-8">
                            <div class="form-group">
                                <div class="form-line">
                                    <p>
                                        <b>Nro de identificación</b>
                                    </p>
                                    <input type="text" class="form-control" name="identificacion" id="identificacion"
                                        placeholder="Ingrese el nro de idenficación." required="">
                                </div>
                            </div>
                        </div>
                        <div class=" col-md-3">
                            <div class="form-group">
                                <div class="button-demo">
                                    <p>
                                        <b>Buscar</b>
                                    </p>
                                    <button type="button" id="boton" onclick="javascript:validarIdentidad();"
                                        class="btn bg-grey waves-effect">
                                        <i class="material-icons">search</i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class=" col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <p>
                                        <b>Nombre</b>
                                    </p>
                                    <input type="text" id="nombre" class="form-control"
                                        placeholder="Nombre del cliente." readonly>
                                </div>
                            </div>
                        </div>
                        <div class=" col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <p>
                                        <b>Apellido</b>
                                    </p>
                                    <input type="text" id="apellido" class="form-control"
                                        placeholder="Apellido del cliente." readonly>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="form-line">
                                    <p>
                                        <b>Dirección</b>
                                    </p>
                                    <input type="text" id="direccion" class="form-control"
                                        placeholder="Dirección del cliente." readonly>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="header" style="background-color:#858392">
                                <h2>
                                    Datos del Reclamo:
                                </h2>
                            </div>
                        </div>
                        <div class=" col-md-6 ">
                            <p>
                                <b>Tipo de servicio</b>
                            </p>
                            <select class="form-control selectpicker" name="codDetContrato" id="id_codDetContrato" required disabled>
                            <option value="{{servicio.codDetContrato}}">---</option>
                            </select>
                        </div>
                        <div class=" col-md-6 ">
                            <p>
                                <b>Categoría</b>
                            </p>
                            <select class="form-control" name="codCategoria" id="id_codCategoria">
                            <option value="-">-----</option>
                            {% for ct in catreclamo %}
                                <option value="{{ ct.codCategoria }}">{{ ct.nombre }}</option>
                            {% endfor %}
                            </select>
                            {{form.codCategoria.errors}}
                        </div>
                        <div class="col-md-12">
                            <p>
                                <b>Descripción</b>
                            </p>
                            <div class="form-group">
                                {{ form.descripcion }}
                                {{ form.descripcion.errors }}
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <a href="{% url 'inicio_atencioncli' %}">
                                            <button type="button" class="btn bg-teal waves-effect">Atrás</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <button type="reset" class="btn bg-blue-grey waves-effect">Limpiar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <button type="button" onclick="javascript:confirmarEnvioReclamo();" class="btn bg-green waves-effect">Enviar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}

{% block javascript %}

<script src="{% static 'js/verificar_cliente.js' %}" type="text/javascript"></script> 
<script src="{% static 'js/mensajes.js' %}" type="text/javascript"></script> 
{% if messages %}
{% for m in messages %}
{% if m.message == "e" %}
<script>
    exitoEnviarReclamo();
</script>
{% endif %}
{% endfor %}
{% endif %}

{% endblock %}

templates/reclamo/cli_crearReclamo.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %}Crear Reclamo | Artemis {% endblock %}

<!--CREAR RECLAMO PARA USUARIOS: CLIENTE -->

{% block content %}
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card">
                <div class="header ">
                    <h2>
                        Registrar Reclamo <small style="color:black; align-justify;">El reclamo es una declaración por
                            el
                            incumplimiento de
                            un servicio que ha sido contratado, ocasionado por la deficiente prestación o suspensión
                            injustificada del servicio.</small>
                    </h2>
                </div>
                <div class="body">
                    <form method="POST" id="formulario">
                        {% csrf_token %}
                        <div class="row clearfix">
                            <input type="hidden" name="nombreUsuario" value="{{ user.nombreUsuario }}"
                                id="id_nombreUsuario">
                            <div class="col-md-2"></div>
                            <div class=" col-md-8">
                                <p>
                                    <b>Tipo de servicio</b>
                                </p>
                                <select class="form-control" name="codDetContrato" required id="id_codDetContrato">
                                    <option value="-">------</option>
                                    {% for servicio in serv %}
                                    <option value="{{servicio.codDetContrato}}">{{ servicio.codServicio.nombre }}
                                    </option>
                                    {% endfor %}
                                </select>
                                {{ form.codDetContrato.errors }}
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-md-2"></div>
                            <div class=" col-md-8">
                                <p>
                                    <b>Categoría</b>
                                </p>
                                <select class="form-control" name="codCategoria" id="id_codCategoria">
                                    <option value="-">------</option>
                                    {% for ct in catreclamo %}
                                    <option value="{{ ct.codCategoria }}">{{ ct.nombre }}</option>
                                    {{ ct.errors }}
                                    {% endfor %}
                                </select>
                                {{form.codCategoria.errors}}
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-md-2"></div>
                            <div class=" col-md-8">
                                <p>
                                    <b>Descripción</b>
                                </p>
                                <div class="form-group">
                                    {{ form.descripcion }}
                                    {{ form.descripcion.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <a href="{% url 'inicio_cliente' %}">
                                            <button type="button" class="btn bg-teal waves-effect">Atrás</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <button type="reset" class="btn bg-blue-grey waves-effect">Limpiar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <button type="button" onclick="javascript:confirmarEnvioReclamo();"
                                            class="btn bg-green waves-effect">Enviar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block javascript %}
<script src="{% static 'js/mensajes.js' %}" type="text/javascript"></script> 
{% if messages %}
{% for m in messages %}
{% if m.message == "e" %}
<script>exitoEnviarReclamo();</script>
{% endif %}
{% endfor %}
{% endif %}

{% endblock %}

templates/reclamo/cli_reclamosfinalizados.html
{% extends "base/base.html" %}
{% load static %}

{% block titulo %} Artemis - Reclamos Finalizados {% endblock titulo %}

<!--LISTADO DE RECLAMOS FINALIZADOS PARA USUARIOS: CLIENTE -->

{% block content %}
<div class="card">
    <div class="header">
        <h2>
            Mis Reclamos Finalizados <small style="color:black; align-justify;">Reclamos finalizados a los que puedes llenar la encuesta de satisfacción</small>
        </h2>
    </div>
    <div class="body table-responsive">
        <table id="tabla-generica" class="table table-bordered nowrap" style="width: 100%">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Categoría</th>
                    <th>Fecha de emisión</th>
                    <th>Fecha de resolución</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Código</th>
                    <th>Categoría</th>
                    <th>Fecha de emisión</th>
                    <th>Fecha de resolución</th>
                    <th>Opciones</th>
                </tr>
            </tfoot>
            <tbody>
            {% for rcf in recfin %}
                <tr>
                    <td>{{rcf.codReclamo}}</td>
                    <td>{{rcf.codCategoria}}</td>
                    <td>{{rcf.fechaRegistro}}</td>
                    <td>{{rcf.fechaFinalizada}}</td>
                    <td>
                        <center><a href="{% url 'encuesta_cliente' rcf.codReclamo %}"> <button type="button"
                                    class="btn bg-black btn-circle waves-effect waves-circle waves-float"><i
                                        class="material-icons">favorite</i></button></a></center>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/pages/tables/tabla-generica.js' %}" type="text/javascript"></script>
<script src="{% static 'js/mensajes.js' %}" type="text/javascript"></script> 
{% if messages %}
{% for m in messages %}
{% if m.message == "e" %}
<script>exitoValoracion();</script>
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}

templates/reclamo/g_listareclamos.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %} Reclamos | Artemis {% endblock %}

<!--LISTADO DE RECLAMOS PARA USUARIOS: GESTOR DE RECLAMOS-->

{% block content %}

<div class="card">
    <div class="header">
        <h2>
            Listado de Reclamos <small style="color:black; align-justify;">Reclamos registradas en el sistema</small>
        </h2>
    </div>
    <div class="body table-responsive">
        <table id="tabla-generica" class="table table-bordered " >
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Nombre del Cliente</th>
                    <th>Fecha de emisión</th>
                    <th>Estado</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Código</th>
                    <th>Nombre del Cliente</th>
                    <th>Fecha de emisión</th>
                    <th>Estado</th>
                    <th>Opciones</th>
                </tr>
            </tfoot>
            <tbody>
            {% for rec in object_list %}
                <tr>
                    <td>{{ rec.codReclamo }}</td>
                    <td>{{ rec.nombreUsuario.idCliente.nombre }} {{ rec.nombreUsuario.idCliente.apellido }}</td>
                    <td>{{ rec.fechaRegistro }}</td>
                    <td>{{ rec.get_estatus_display }}</td>
                    <td>
                        <center><a href="{% url 'gt_consultarReclamo' rec.codReclamo %}"> <button type="button"
                                class="btn bg-black btn-circle waves-effect waves-circle waves-float"><i
                                    class="material-icons">remove_red_eye</i></button></a></center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

{% block javascript %}
<script src="{% static 'js/pages/tables/tabla-generica.js' %}" type="text/javascript"></script>
{% endblock %}