Artemis/urls.py
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('', include('apps.index.urls')),
    path('', include('pwa.urls')),
    path('djangoadmin/', admin.site.urls),
    path('usuario/', include('apps.usuario.urls')),
    path('reclamo/', include('apps.reclamo.urls')),
    path('resp_predefinida/', include('apps.resp_predefinida.urls')),
    path('pqs/', include('apps.pqs.urls')),
    path('datosexternos/', include('apps.datos_externos.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard_checker, name='dashboard_checker'),
    path('inicio/gestreclamo/', views.inicio_gestreclamo.as_view(), name='inicio_gestreclamo'),
    path('inicio/cliente/', views.inicio_cliente.as_view(), name='inicio_cliente'),
    path('inicio/atencioncli/', views.inicio_atencioncli.as_view(), name='inicio_atencioncli'),
    path('inicio/gestorPQS/', views.inicio_gestorpqs.as_view(), name='inicio_gestorpqs'),
    path('inicio/tecnico/', views.inicio_tecnico.as_view(), name='inicio_tecnico'),
    path('inicio/admin/', views.inicio_admin.as_view(), name='inicio_admin'),
    path('inicio/gerente/', views.inicio_gerente, name='inicio_gerente'),
    path('empleados/crear/', views.crear_empleado.as_view(), name='crear_empleado'),
    path('perfil/', views.perfil, name='perfil'),
    path('perfil/modificar/', views.modificar_perfil.as_view(), name='modificar_perfil'),
    path('clientes/lista/', views.listacliente.as_view(), name='listacliente'),
    path('clientes/ver/<pk>/', views.consultarcliente.as_view(), name='consultarcliente'),
    path('empleados/lista/', views.lista_empleados.as_view(), name='lista_empleados'),
    path('empleados/ver/<pk>/', views.consultar_empleado.as_view(), name='consultar_empleado'),
    path('cliente/pqrs/lista/', views.lista_pqrscliente.as_view(), name='lista_pqrscliente'),
    path('reporte/fallas/', views.reporte_fallas.as_view(), name='reporte_fallas'),
    path('reporte/satisfaccionclientes/', views.reporte_encuestas.as_view(), name='reporte_encuestas'),
    path('reporte/pqsmarcadas/', views.reporte_pqs.as_view(), name='reporte_pqs'),
    path('notificaciones/todas', views.lista_notificaciones.as_view(), name='lista_notificaciones'),
]

usuario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('petitionlist/', views.petitionlist, name='petitionlist'),
]

apps/pqs/models.py
from django.db import models
from apps.usuario.models import User
from datetime import datetime
from notifications.signals import notify

# Create your models here.
class PQS(models.Model):

    def cod_pqs():
        pqs = PQS
        ult_pqs = pqs.objects.all().count()

        if not ult_pqs:
            return 'PQS-0000'

        nro_pqs = int(ult_pqs)
        nvo_codpqs = 'PQS-' + str(nro_pqs).zfill(4) 

        return nvo_codpqs

    codPQS = models.CharField(max_length=8,default=cod_pqs, primary_key=True)
    nombreUsuario = models.ForeignKey(User, related_name='creador', on_delete=models.CASCADE, blank=False, null=False)
    CATEGORIA = (
        ('P','Peticion'),
        ('Q','Queja'),
        ('S','Sugerencia'),
    )
    categoria = models.CharField(max_length=1,choices=CATEGORIA, blank=False, null=False)
    descripcion = models.CharField(max_length=500)
    fechaRegistro = models.DateTimeField(default=datetime.now)
    fechaFinalizado = models.DateTimeField(blank=True ,null=True)
    responsablePQS = models.ManyToManyField(User, related_name='responsable', blank=True)
    ESTATUS = ( 
        ('P','Pendiente'),
        ('M','Marcada'),
        ('A','Atendida'),
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='P')

    def __str__(self):
        return self.codPQS + ' / ' + self.nombreUsuario.nombreUsuario +' / ' + self.nombreUsuario.idCliente.nombre + ' / ' + self.descripcion[:20] + '...'

class HistoricoPQS(models.Model):
    pqs = models.ForeignKey(PQS, on_delete=models.CASCADE,blank=True, null=True)
    fecha = models.DateField(auto_now = True, blank=True, null=True)
    detalle = models.CharField(max_length = 200)
    usuarioEncargado = models.CharField(max_length = 20)

    def notificar(self, descripcion):
        notify.send(sender=self, recipient=self.pqs.nombreUsuario, verb='n', description=descripcion)

    def __str__(self):
        return self.pqs.codPQS

apps/usuario/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from apps.datos_externos.models import Empleado, Cliente
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

# Create your models here.
class TipoUser(models.Model):
    codTipoUser = models.CharField(max_length=8, primary_key=True)
    tipoUser = models.CharField(max_length=10)
    ESTATUS = ( 
        ('A','Activo'),
        ('I','Inactivo'),
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')

    def __str__(self):
        return self.tipoUser

class UserManager(BaseUserManager):
    def create_user(self, nombreUsuario, idCliente, idEmpleado, correo, is_staff=False, is_superuser=False, codTipoUser='cli', estatus='A', password = None):
        user_obj = self.model(
            correo=self.normalize_email(correo)
        )
        user_obj.set_password(password)
        user_obj.nombreUsuario = nombreUsuario
        user_obj.idCliente = Cliente.objects.get(identificacion=idCliente)
        user_obj.idEmpleado = Empleado.objects.get(identificacion=idEmpleado)
        user_obj.codTipoUser = TipoUser.objects.get(codTipoUser=codTipoUser)
        user_obj.correo = correo
        user_obj.estatus = estatus
        user_obj.is_staff = is_staff
        user_obj.is_superuser = is_superuser
        user_obj.save(using=self._db)
        return user_obj

    def create_superuser(self, nombreUsuario, correo, idEmpleado, idCliente = '0', is_staff=True, is_superuser=True, codTipoUser='admin', estatus='A', password=None):
        user = self.create_user(
            nombreUsuario,
            idCliente,
            idEmpleado,
            correo,
            is_staff,
            is_superuser,
            codTipoUser,
            estatus,
            password=password,
        )
        return user

class User(AbstractBaseUser,PermissionsMixin):
    nombreUsuario = models.CharField(max_length=20, primary_key=True, unique=True,verbose_name='nombre de usuario')
    idEmpleado = models.OneToOneField(Empleado,on_delete=models.CASCADE, blank=True, null=True, verbose_name='identificación del empleado')  
    idCliente = models.OneToOneField(Cliente, on_delete=models.CASCADE, blank=True, null=True, verbose_name='identificación del cliente')
    codTipoUser = models.ForeignKey(TipoUser, on_delete=models.CASCADE, blank=True, null=True, default = 'cli', verbose_name='tipo de usuario')
    correo = models.EmailField(max_length=30,unique=True, verbose_name='correo electrónico')
    foto = models.ImageField(upload_to='usuarios/fotos/', default='usuarios/fotos/default.jpg')
    ESTATUS = ( 
        ('A','Activo'),
        ('I','Inactivo'),
    )
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')
    USERNAME_FIELD = 'nombreUsuario'
    EMAIL_FIELD = 'correo'
    REQUIRED_FIELDS = ['correo','idEmpleado']

    objects = UserManager()

    def enviarCorreo(self, asunto, linea1, linea2="", linea3=""):
        nombre = self.idCliente.nombre + " " + self.idCliente.apellido
        contenido = render_to_string('correo_base.html',{'linea1':linea1,'linea2':linea2,'linea3':linea3,'nombre':nombre})
        send_mail('Artemis - ' + asunto,strip_tags(contenido),'admin@artemis.com',{self.correo},html_message=contenido)

    def login_grec(self):
        if self.last_login:
            last_login = self.last_login.date()
            hoy = timezone.now().date()
            if last_login != hoy:
                eg = EficienciaGestor.objects.get(nombreUsuario = self)
                eg.diasActivo += 1
                eg.save()
                self.actualizar_eficiencia()
        else:
            eg = EficienciaGestor.objects.get(nombreUsuario = self)
            eg.diasActivo += 1
            eg.save()
            self.actualizar_eficiencia()

    def actualizar_eficiencia(self):
        eg = EficienciaGestor.objects.get(nombreUsuario = self)
        eg.eficiencia = eg.recAtendidos / eg.diasActivo
        eg.save()

    class Meta:
        verbose_name = 'usuario'
        verbose_name_plural = 'usuarios'

class EficienciaGestor(models.Model):
    nombreUsuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    diasActivo = models.IntegerField(default=0)
    recAtendidos = models.IntegerField(default=0)
    eficiencia = models.FloatField(default=0.001)

@receiver(post_save, sender=User)
def crear_eficiciencia(sender, instance, **kwargs):
    try:
        EficienciaGestor.objects.get(nombreUsuario = instance.nombreUsuario)
    except:
        if instance.codTipoUser.codTipoUser == "grec":
            eg = EficienciaGestor()
            eg.nombreUsuario = instance
            eg.save()

apps/usuario/forms.py
from django import forms 
from .models import User
from django.contrib.auth.forms import UserCreationForm

class ActualizarUsuarioForm(forms.ModelForm):

    class Meta:
        model = User

        fields = [
            'correo',
            'foto',
        ]

        widgets = {
            'correo' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ingresar la dirección de correo aquí.'}),
            'foto' : forms.FileInput(),
        }

class CrearUsuario(UserCreationForm):

    class Meta:
        model = User

        fields = [
            'idEmpleado',
            'nombreUsuario',
            'password1',
            'correo',
            'codTipoUser',
            'idCliente',
        ]

        widgets = {
            'idEmpleado' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ingresa la identificación aquí.'}),
            'nombreUsuario' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ingresa el nombre de usuario aquí.'}),
            'password1' : forms.PasswordInput(),
            'password2' : forms.PasswordInput(),
            'correo' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ingresa la dirección de correo aquí.'}),
            'codTipoUser' : forms.Select(attrs={'class':'form-control'}),
            'idCliente' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ingresa la identificación aquí.'})
        }  

class ConsultarEmpleado(forms.ModelForm):

    class Meta:
        model = User

        fields = [
            'nombreUsuario',
            'correo',
            'estatus',
            'is_active',
        ]

        widgets = {
            'nombreUsuario' : forms.TextInput(attrs={'class':'form-control','readonly':''}),
            'correo' : forms.TextInput(attrs={'class':'form-control','readonly':''}),
            'estatus' : forms.TextInput(attrs={'class':'form-control','id':'estatus','type':'hidden'}),
            'is_active' : forms.TextInput(attrs={'class':'form-control','id':'is_active','type':'hidden'}),
        }   

class ConsultarCliente(forms.ModelForm):

    class Meta:
        model = User   

        fields = [
            'nombreUsuario',
            'correo',
            'estatus',
            'is_active',
        ]

        widgets = {
            'nombreUsuario' : forms.TextInput(attrs={'class':'form-control','readonly':''}),
            'correo': forms.TextInput(attrs={'class':'form-control','readonly':''}),
            'estatus' : forms.TextInput(attrs={'class':'form-control','id':'estatus','type':'hidden'}),
            'is_active' : forms.TextInput(attrs={'class':'form-control','id':'is_active','type':'hidden'}),
        }

usuario/views.py
from django.shortcuts import render

# Create your views here.

def dashboard(request):
    return render(request, 'usuario/dashboard.html', {})

def petitionlist(request):
    return render(request, 'peticion/petitionlist.html', {})

templates/usuario/gestpqs/g_listapqs.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %} Listado PQS | Artemis {% endblock %}

<!--LISTADO DE PQS PARA USUARIO: GESTOR DE PQS-->
{% block content %}

<div class="card">
    <div class="header">
        <h2>
            Listado de PQS <small style="color:#171d40; align-justify;">Peticiones, quejas y sugerencias registradas en el sistema.</small>
        </h2>
    </div>
    <div class="body">
        <div class="table-responsive">
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="form-line">
                                <p>
                                    <b style="color:black">Filtrar</b>
                                </p>
                                <select class="form-control show-tick">
                                    <option>Petición</option>
                                    <option>Queja</option>
                                    <option>Reclamo</option>
                                    <option>Sugerencia</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <table id="table-list" class="table table-bordered table-hover nowrap" style="width: 100%">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nombre de usuario</th>
                                <th>Categoría</th>
                                <th>Fecha de emisión</th>
                                <th>Asunto</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Código</th>
                                <th>Nombre de usuario</th>
                                <th>Categoría</th>
                                <th>Fecha de emisión</th>
                                <th>Estado</th>
                                <th>Opciones</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <tr>
                                <th>PT-01</th>
                                <td>sara21</td>
                                <td>Petición</td>
                                <td>2019/06/30</td>
                                <td>Sin revisión</td>
                                <td>
                                    <center><button type="button"
                                            class="btn bg-black btn-circle waves-effect waves-circle waves-float"><i
                                                class="material-icons">remove_red_eye</i></button></center>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/usuario/gestpqs/inicio_gestorpqs.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %} Bienvenido | Artemis {% endblock %}

{% block content %}

<div class="block-header">
    <h2>LISTADOS</h2> 
</div>

<div class="row clearfix">
    <a href="{% url 'g_listapqs' %}">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box-3  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">question_answer</i>
                </div>
                <div class="content">
                    <div class="text" style="color:white">PQS Pendientes</div>
                    <div class="number count-to" style="color:white" data-from="0" data-to="{{ cant_pen }}" data-speed="1500"
                        data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
    </a>
    <a href="{% url 'pqsmarcados' %}">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box-3  hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">question_answer</i>
                </div>
                <div class="content">
                    <div class="text" style="color:white">PQS Marcadas</div>
                    <div class="number count-to" style="color:white" data-from="0" data-to="{{ cant_mar }}" data-speed="1500"
                        data-fresh-interval="20"></div>
                </div>
            </div>
        </div>
    </a>
</div>
<div class="block-header">
    <h2>REPORTES</h2> 
</div>
<div class="row clearfix">
    <a href="{% url 'reporte_pqsmarcados' %}">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box-3 hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">loyalty</i>
                </div>
                <div class="content">
                    <div class="text" style="color:white">PQS</div>
                    <div class="number" style="color:white">Marcadas</div>
                </div>
            </div>
        </div>
    </a>
</div>



<div class="card">
    <div class="header">
        <h2>
            Listado de PQS <small style="color:black; align-justify;">PQS recibidas...</small>
        </h2>
    </div>
    <div class="body">
        <div class="table-responsive">
            <table id="tabla-gestpqs" class="table table-bordered " >
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Categoría</th>
                        <th>Nombre del cliente</th>
                        <th>Estado</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Código</th>
                        <th>Categoría</th>
                        <th>Nombre del cliente</th>
                        <th>Estado</th>                   
                        <th>Opciones</th>
                    </tr>
                </tfoot>
                <tbody>
                {% for pqs in object_list %}
                    <tr>
                        <td> {{ pqs.codPQS }} </td>
                        <td> {{ pqs.get_categoria_display }} </td>
                        <td> {{ pqs.nombreUsuario.idCliente.nombre }} {{ pqs.nombreUsuario.idCliente.apellido }} </td>
                        <td>{{ pqs.get_estatus_display }} </td>
                        <td> 
                            <center><a href="{% url 'consultarpqs' pqs.codPQS %}">
                            <button type="button"
                                    class="btn bg-black btn-circle waves-effect waves-circle waves-float"><i
                                        class="material-icons">remove_red_eye</i></button></a></center>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}

<script src="{% static 'js/pages/tables/tabla-gestorpqs.js' %}" type="text/javascript"></script>

{% endblock %}