Artemis/urls.py
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('', include('apps.index.urls')),
    path('', include('pwa.urls')),
    path('djangoadmin/', admin.site.urls),
    path('usuario/', include('apps.usuario.urls')),
    path('reclamo/', include('apps.reclamo.urls')),
    path('resp_predefinida/', include('apps.resp_predefinida.urls')),
    path('pqs/', include('apps.pqs.urls')),
    path('datosexternos/', include('apps.datos_externos.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuario/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from apps.datos_externos.models import Empleado, Cliente
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

# Create your models here.
class TipoUser(models.Model):
    codTipoUser = models.CharField(max_length=8, primary_key=True)
    tipoUser = models.CharField(max_length=10)
    ESTATUS = ( 
        ('A','Activo'),
        ('I','Inactivo'),
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')

    def __str__(self):
        return self.tipoUser

class UserManager(BaseUserManager):
    def create_user(self, nombreUsuario, idCliente, idEmpleado, correo, is_staff=False, is_superuser=False, codTipoUser='cli', estatus='A', password = None):
        user_obj = self.model(
            correo=self.normalize_email(correo)
        )
        user_obj.set_password(password)
        user_obj.nombreUsuario = nombreUsuario
        user_obj.idCliente = Cliente.objects.get(identificacion=idCliente)
        user_obj.idEmpleado = Empleado.objects.get(identificacion=idEmpleado)
        user_obj.codTipoUser = TipoUser.objects.get(codTipoUser=codTipoUser)
        user_obj.correo = correo
        user_obj.estatus = estatus
        user_obj.is_staff = is_staff
        user_obj.is_superuser = is_superuser
        user_obj.save(using=self._db)
        return user_obj

    def create_superuser(self, nombreUsuario, correo, idEmpleado, idCliente = '0', is_staff=True, is_superuser=True, codTipoUser='admin', estatus='A', password=None):
        user = self.create_user(
            nombreUsuario,
            idCliente,
            idEmpleado,
            correo,
            is_staff,
            is_superuser,
            codTipoUser,
            estatus,
            password=password,
        )
        return user

class User(AbstractBaseUser,PermissionsMixin):
    nombreUsuario = models.CharField(max_length=20, primary_key=True, unique=True,verbose_name='nombre de usuario')
    idEmpleado = models.OneToOneField(Empleado,on_delete=models.CASCADE, blank=True, null=True, verbose_name='identificación del empleado')  
    idCliente = models.OneToOneField(Cliente, on_delete=models.CASCADE, blank=True, null=True, verbose_name='identificación del cliente')
    codTipoUser = models.ForeignKey(TipoUser, on_delete=models.CASCADE, blank=True, null=True, default = 'cli', verbose_name='tipo de usuario')
    correo = models.EmailField(max_length=30,unique=True, verbose_name='correo electrónico')
    foto = models.ImageField(upload_to='usuarios/fotos/', default='usuarios/fotos/default.jpg')
    ESTATUS = ( 
        ('A','Activo'),
        ('I','Inactivo'),
    )
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='A')
    USERNAME_FIELD = 'nombreUsuario'
    EMAIL_FIELD = 'correo'
    REQUIRED_FIELDS = ['correo','idEmpleado']

    objects = UserManager()

    def enviarCorreo(self, asunto, linea1, linea2="", linea3=""):
        nombre = self.idCliente.nombre + " " + self.idCliente.apellido
        contenido = render_to_string('correo_base.html',{'linea1':linea1,'linea2':linea2,'linea3':linea3,'nombre':nombre})
        send_mail('Artemis - ' + asunto,strip_tags(contenido),'admin@artemis.com',{self.correo},html_message=contenido)

    def login_grec(self):
        if self.last_login:
            last_login = self.last_login.date()
            hoy = timezone.now().date()
            if last_login != hoy:
                eg = EficienciaGestor.objects.get(nombreUsuario = self)
                eg.diasActivo += 1
                eg.save()
                self.actualizar_eficiencia()
        else:
            eg = EficienciaGestor.objects.get(nombreUsuario = self)
            eg.diasActivo += 1
            eg.save()
            self.actualizar_eficiencia()

    def actualizar_eficiencia(self):
        eg = EficienciaGestor.objects.get(nombreUsuario = self)
        eg.eficiencia = eg.recAtendidos / eg.diasActivo
        eg.save()

    class Meta:
        verbose_name = 'usuario'
        verbose_name_plural = 'usuarios'

class EficienciaGestor(models.Model):
    nombreUsuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    diasActivo = models.IntegerField(default=0)
    recAtendidos = models.IntegerField(default=0)
    eficiencia = models.FloatField(default=0.001)

@receiver(post_save, sender=User)
def crear_eficiciencia(sender, instance, **kwargs):
    try:
        EficienciaGestor.objects.get(nombreUsuario = instance.nombreUsuario)
    except:
        if instance.codTipoUser.codTipoUser == "grec":
            eg = EficienciaGestor()
            eg.nombreUsuario = instance
            eg.save()

templates/index/cambiar_contrasena.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %} Artemis {% endblock %}

{% block content %}


<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card">
            <div class="card">
                <div class="header">
                    <h2>
                        Cambiar Contraseña Actual
                    </h2>
                </div>
                <div class="body">
                    <form method="POST" id="formulario">
                        {% csrf_token %}
                        {{form.errors.as_p}}
                        <div class="row clearfix">
                            <div class="col-md-3"></div>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <p>
                                            <b>Contraseña Actual</b>
                                        </p>
                                        <input type="password" id="id_old_password" name="old_password" required
                                            class="form-control" placeholder="Ingrese la nueva contraseña">
                                    </div>
                                    {{form.old_password.errors}}
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-md-3"></div>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <p>
                                            <b>Contraseña Nueva</b>
                                        </p>
                                        <input type="password" id="id_new_password_1" name="new_password1"
                                            id="id_new_password1" class="form-control"
                                            placeholder="Ingrese la nueva contraseña" required="">
                                    </div>
                                </div>
                                {{ form.new_password1.errors }}
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-md-3"></div>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <p>
                                            <b>Confirmar contraseña</b>
                                        </p>
                                        <input type="password" id="id_new_password2" name="new_password2"
                                            class="form-control" placeholder="Confirme la nueva contraseña" required="">
                                    </div>
                                </div>
                                {{ form.new_password2.errors }}
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <a
                                            href="{% if user.codTipoUser.codTipoUser == 'cli' %} {% url 'inicio_cliente' %} {% elif user.codTipoUser.codTipoUser == 'atc' %}{% url 'inicio_atencioncli' %}{% elif user.codTipoUser.codTipoUser == 'admin' %}{% url 'inicio_admin' %}{% elif user.codTipoUser.codTipoUser == 'ger'%}{% url 'inicio_gerente' %}{% elif user.codTipoUser.codTipoUser == 'tec' %} {% url 'inicio_tecnico' %} {% elif user.codTipoUser.codTipoUser == 'gpqs' %} {% url 'inicio_gestorpqs' %} {% elif user.codTipoUser.codTipoUser == 'grec' %} {% url 'inicio_gestreclamo' %} {% endif %}">
                                            <button type="button" class="btn bg-teal waves-effect">Cancelar</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <button type="reset" class="btn bg-blue-grey waves-effect">Limpiar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <button type="button" onclick="javascript:confirmarCambiarContraseña();"
                                            class="btn bg-green waves-effect">Cambiar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block javascript %}
<script src="{% static 'js/mensajes.js' %}" type="text/javascript"></script>
{% for m in messages %}
{% if m.message == "ec" %}
<script>
    swal("Cambiada", "La contraseña ha sido cambiada con éxito.", "success");
</script>
{% endif %}
{% endfor %}
{% endblock %}

templates/index/forgotpassword.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>¿Olvidó sus credenciales? | Artemis</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static "plugins/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static "plugins/node-waves/waves.css" %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static "plugins/animate-css/animate.css" %}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>

<body class="fp-page">
    <div class="fp-box">
        <div class="logo">
            <img class="img-responsive" src="{% static 'images/logo.png' %}" style="width:450px; display:table-cell;"><br/><br/>
            <small>Artemis - Sistema de Gestión de PQRS</small>
        </div>
        <div class="card">
            <div class="body">
                <form id="forgot_password" method="POST">
                    <div class="msg" style="align-justify">
                        Ingrese su dirección de correo electrónico y le enviaremos un mensaje con su nombre de usuario y un link para que pueda cambiar su contraseña de forma segura.
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">email</i>
                        </span>
                        <div class="form-line">
                            <input type="email" class="form-control" name="email" placeholder="Correo Electronico" required autofocus>
                        </div>
                    </div>

                    <button class="btn btn-block btn-lg bg-blue-grey waves-effect" type="submit">Recuperar mis credenciales</button>

                    <div class="row m-t-20 m-b--5 align-center">
                        <a href="{% url 'index' %}">¡Inicia Sesión!</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{% static "plugins/jquery/jquery.min.js" %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static "plugins/bootstrap/js/bootstrap.js" %}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static "plugins/node-waves/waves.js" %}"></script>

    <!-- Validation Plugin Js -->
    <script src="{% static "plugins/jquery-validation/jquery.validate.js" %}"></script>

    <!-- Custom Js -->
    <script src="{% static "js/admin.js" %}"></script>
    <script src="{% static "js/pages/examples/forgot-password.js" %}"></script>
</body>

</html>

<!--JS-->
<script>
    function confirmarSeleccion() {
        swal({
            title: "Confirmar creación",
            text: "¿Está seguro que desea recuperar sus credenciales?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#58a05d",
            confirmButtonText: "Sí",
            cancelButtonText: "Cancelar",
            closeOnConfirm: false,
            closeOnCancel: false
        }, function (isConfirm) {
            if (isConfirm) {
                formulario.submit();
            } else {
                swal("Cancelada", "La solicitud no ha sido enviada.", "error");
            }
        });
    }
</script>

templates/index/index.html
<!DOCTYPE html>
<html>
{% load static %}
{% load pwa %}

<head>
    {% progressive_web_app_meta %}
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Iniciar Sesión - Artemis</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet"
        type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static "plugins/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static "plugins/node-waves/waves.css" %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static "plugins/animate-css/animate.css" %}" rel="stylesheet" />

    <link href="{% static "plugins/sweetalert/sweetalert.css" %}" rel="stylesheet">

    <!-- Custom Css -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <!-- Json -->
    <link rel="manifest" href="/manifest.json">
</head>

<body class="login-page">
    <div class="login-box">
        <div class="logo">
            <a href="{% url 'index' %}"><img class="img-responsive" src="{% static 'images/logo.png' %}"
                    style="width:450px; display:table-cell;"></a><br /><br />
            <small>Artemis - Sistema de Gestión de PQRS</small>
        </div>
        <div class="card">
            <div class="body">
                <form id="sign_in" method="POST">
                    {% csrf_token %}
                    <div class="msg">Inicia sesión para utilizar el sistema</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" id="login_username" name="username"
                                placeholder="Nombre de Usuario" required autofocus>
                        </div>
                        {{ form.username.errors }}
                        {{ form.username.help_text }}
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="password" placeholder="Contraseña"
                                required>
                        </div>
                        {{ form.password.errors }}
                        {{ form.password.help_text }}
                    </div>
                    {% if form.errors %}
                    <h5 style="color:red;">Datos incorrectos</h5>
                    {% endif %}
                    <div class="row">
                        <div class="col-xs-8 p-t-5">
                            <input type="checkbox" name="rememberme" id="rememberme"
                                class="filled-in chk-col-blue-grey">
                            <label for="rememberme">Recuerdame</label>
                        </div>
                        <div class="col-xs-4">
                            <button class="btn btn-block bg-green waves-effect" type="submit">ACCEDER</button>
                        </div>
                    </div>
                    <div class="row m-t-15 m-b--20">
                        <div class="col-xs-6">
                            <a href="{% url 'signup' %}">¡Regístrate ahora!</a>
                        </div>
                        <div class="col-xs-6 align-center">
                            <a href="{% url 'reset' %}">¿Olvidó sus credenciales?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{% static "plugins/jquery/jquery.min.js" %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static "plugins/bootstrap/js/bootstrap.js" %}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static "plugins/node-waves/waves.js" %}"></script>

    <!-- Validation Plugin Js -->
    <script src="{% static "plugins/jquery-validation/jquery.validate.js" %}"></script>

    <!-- Custom Js -->
    <script src="{% static "js/admin.js" %}"></script>
    <script src="{% static "js/pages/examples/sign-in.js" %}"></script>

    <!-- Custom Css -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <script src="{% static 'plugins/sweetalert/sweetalert.min.js' %}" type="text/javascript"></script>

    {% for m in messages %}
    {% if m.message == "u" %}
    <!--MENSAJE CREAR USUARIO-->
    <script>
        swal("Creada", "El usuario ha sido creado con éxito.", "success");
    </script>
    {% elif m.message == "c" %}
    <!--MENSAJE RECUPERAR CREDENCIALES-->
    <script>
        swal("Creada", "El usuario ha sido creado con éxito.", "success");
    </script>
    {% endif %}
    {% endfor %}
</body>

</html>

templates/index/signup.html
{% load static %}
{% load myfilters %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>¡Registrate! | Artemis</title>
    <!-- Favicon-->
    <link rel="icon"
        href="{% static "favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css" %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css" %}">

    <!-- Bootstrap Core Css -->
    <link href="{% static "plugins/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static "plugins/node-waves/waves.css" %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static "plugins/animate-css/animate.css" %}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "plugins/sweetalert/sweetalert.css" %}" rel="stylesheet">
</head>

<body class="signup-page">
    <div class="signup-box">
        <div class="logo">
            <a href="{% url 'index' %}"><img class="img-responsive" src="{% static 'images/logo.png' %}"
                    style="width:450px; display:table-cell;"></a><br /><br />
            <small>Artemis - Sistema de Gestión de PQRS</small>
        </div>
        <div class="card">
            <div class="body">
                <form id="formulario" method="POST">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                    <div class="non-field-errors">
                        {% for err in form.non_field_errors %}
                        <p class="form-error">{{ err }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="msg">¡Resgístrate para poder enviar PQRS!</div>
                    <input name="codTipoUser" class="form-control" id="id_codTipoUser" value="cli" type="hidden">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">supervised_user_circle</i>
                        </span>
                        <div class="form-line">
                            {{ form.nombreUsuario | addclass:'form-control,Nombre de Usuario' }}
                        </div>
                        {{ form.nombreUsuario.errors }}
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            {{ form.idCliente | addclass:'form-control,Identificacion' }}
                        </div>
                        {{ form.idCliente.errors }}
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">email</i>
                        </span>
                        <div class="form-line">
                            {{ form.correo | addclass:'form-control,Correo' }}
                        </div>
                        {{ form.correo.errors }}
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            {{ form.password1 | addclass:'form-control,Contraseña' }}
                        </div>
                        {{ form.password1.erros }}
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            {{ form.password2 | addclass:'form-control,Confirmar Contraseña' }}
                        </div>
                        {{ form.password2.errors }}
                    </div>

                    <button class="btn btn-block btn-lg bg-green waves-effect"
                        onclick="javascript:confirmarSeleccion();" type="button">Registrar</button>

                    <div class="m-t-25 m-b--5 align-center">
                        <a href="{% url 'index' %}">¿Ya tienes una cuenta?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{% static "plugins/jquery/jquery.min.js" %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static "plugins/bootstrap/js/bootstrap.js" %}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static "plugins/node-waves/waves.js" %}"></script>

    <!-- Validation Plugin Js -->
    <script src="{% static "plugins/jquery-validation/jquery.validate.js" %}"></script>

    <!-- Custom Js -->
    <script src="{% static "js/admin.js" %}"></script>
    <script src="{% static "js/pages/examples/sign-up.js" %}"></script>
    <script src="{% static 'plugins/sweetalert/sweetalert.min.js' %}" type="text/javascript"></script>
</body>

</html>

<!--JS-->
<script>
    function confirmarSeleccion() {
        if ($('#id_idCliente').val()!=''){
            swal({
                title: "Confirmar creación",
                text: "¿Está seguro que desea crear el usuario?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#58a05d",
                confirmButtonText: "Sí",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                if (isConfirm) {
                    formulario.submit();
                } else {
                    swal("Cancelada", "El usuario no ha sido creado.", "error");
                }
            });
        } else {
            swal("Error","La identificación del usuario no puede estar vacía", "warning");  
        }
    }
</script>

{% for m in messages %}
{% if m.message == "u" %}
<!--MENSAJE CREAR USUARIO-->
<script>
    swal("Creada", "El usuario ha sido creado con éxito.", "success");
</script>
{% elif m.message == "c" %}
<!--MENSAJE RECUPERAR CREDENCIALES-->
<script>
    swal("Creada", "El usuario ha sido creado con éxito.", "success");
</script>
{% endif %}
{% endfor %}