Artemis/urls.py
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('', include('apps.index.urls')),
    path('', include('pwa.urls')),
    path('djangoadmin/', admin.site.urls),
    path('usuario/', include('apps.usuario.urls')),
    path('reclamo/', include('apps.reclamo.urls')),
    path('resp_predefinida/', include('apps.resp_predefinida.urls')),
    path('pqs/', include('apps.pqs.urls')),
    path('datosexternos/', include('apps.datos_externos.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pqs/models.py
from django.db import models
from apps.usuario.models import User
from datetime import datetime
from notifications.signals import notify

# Create your models here.
class PQS(models.Model):

    def cod_pqs():
        pqs = PQS
        ult_pqs = pqs.objects.all().count()

        if not ult_pqs:
            return 'PQS-0000'

        nro_pqs = int(ult_pqs)
        nvo_codpqs = 'PQS-' + str(nro_pqs).zfill(4) 

        return nvo_codpqs

    codPQS = models.CharField(max_length=8,default=cod_pqs, primary_key=True)
    nombreUsuario = models.ForeignKey(User, related_name='creador', on_delete=models.CASCADE, blank=False, null=False)
    CATEGORIA = (
        ('P','Peticion'),
        ('Q','Queja'),
        ('S','Sugerencia'),
    )
    categoria = models.CharField(max_length=1,choices=CATEGORIA, blank=False, null=False)
    descripcion = models.CharField(max_length=500)
    fechaRegistro = models.DateTimeField(default=datetime.now)
    fechaFinalizado = models.DateTimeField(blank=True ,null=True)
    responsablePQS = models.ManyToManyField(User, related_name='responsable', blank=True)
    ESTATUS = ( 
        ('P','Pendiente'),
        ('M','Marcada'),
        ('A','Atendida'),
    )
    estatus = models.CharField(max_length=1,choices=ESTATUS, default='P')

    def __str__(self):
        return self.codPQS + ' / ' + self.nombreUsuario.nombreUsuario +' / ' + self.nombreUsuario.idCliente.nombre + ' / ' + self.descripcion[:20] + '...'

class HistoricoPQS(models.Model):
    pqs = models.ForeignKey(PQS, on_delete=models.CASCADE,blank=True, null=True)
    fecha = models.DateField(auto_now = True, blank=True, null=True)
    detalle = models.CharField(max_length = 200)
    usuarioEncargado = models.CharField(max_length = 20)

    def notificar(self, descripcion):
        notify.send(sender=self, recipient=self.pqs.nombreUsuario, verb='n', description=descripcion)

    def __str__(self):
        return self.pqs.codPQS

templates/peticion/atc_crearpeticion.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %}Crear Petición | Artemis {% endblock %}

{% block content %}
<div class="card">
    <div class="header">
        <h2>
            Registrar Petición <small style="color:black; text-align:justify;">Una petición es aquello que puede
                solicitar o reclamar ante la empresa por razones
                de interés general o interés particular, así elevar solicitudes de información y/o consulta y para
                obtener una resolución de las mismas.</small>
        </h2>
    </div>
    <div class="body">
    <form method="POST" id="formulario">
    {% csrf_token %}
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="col-md-6">
                    <div class="col-xs-12">
                        <div class="header" style="background-color:#858392">
                            <h2>
                                Datos del cliente:
                            </h2>
                        </div>
                    </div>
                    {{ form.nombreUsuario }}
                    <div class="col-md-8">
                        <div class="form-group">
                            <div class="form-line">
                                <p>
                                    <b>Nro de identificación</b>
                                </p>
                                <input type="text" class="form-control" name="identificacion" id="identificacion" placeholder="Ingrese el nro de idenficación.">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <p>
                                <b>Buscar</b>
                            </p>
                            <div class="button-demo">
                                <button type="button" id="boton" onclick="javascript:validarIdentidad();" class="btn bg-grey waves-effect waves-effect btn-md">
                                    <i class="material-icons">search</i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-line">
                                <p>
                                    <b>Nombre</b>
                                </p>
                                <input type="text" id="nombre" class="form-control" placeholder="Nombre del cliente." readonly>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-line">
                                <p>
                                    <b>Apellido</b>
                                </p>
                                <input type="text" id="apellido" class="form-control" placeholder="Apellido del cliente." readonly>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="form-line">
                                <p>
                                    <b>Dirección</b>
                                </p>
                                <input type="text" id="direccion" class="form-control" placeholder="Dirección del cliente." readonly>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-xs-12">
                        <div class="header" style="background-color:#858392">
                            <h2>
                                Datos la Petición:
                            </h2>
                        </div>
                    </div>
                    <div class=" col-md-12">
                        <div class="form-group">
                            <p>
                                <b>Descripción</b>
                            </p>
                            <div class="form-line">
                                {{ form.descripcion }}
                                {{ form.descripcion.errors}}
                            </div>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="categoria" id="id_categoria" class="form-control" value="P" required>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="button-demo">
                                <a href="{% url 'inicio_atencioncli' %}">
                                    <button type="button" class="btn bg-teal waves-effect">Atrás</button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="button-demo">
                                <button type="reset" class="btn bg-blue-grey waves-effect">Limpiar</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="button-demo">
                                <button type="button" onclick="javascript:confirmarPeticion();" class="btn bg-green waves-effect">Enviar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    </div>
</div>


{% endblock %}

{% block javascript %}
<script src="{% static 'js/verificar_cliente.js' %}" type="text/javascript"></script> 
<script src="{% static 'js/mensajes.js' %}" type="text/javascript"></script> 
{% if messages %}
{% for m in messages %}
{% if m.message == "e" %}
<script>exitoPeticion();</script>
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}

templates/peticion/cli_crearpeticion.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %}Crear Petición | Artemis {% endblock %}

{% block content %}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card">
                <div class="header">
                    <h2 >
                        Registrar Petición <small style="color:black; align-justify;">Una petición es aquello que puede solicitar o
                            reclamar ante la empresa por razones
                            de interés general o interés particular, así elevar solicitudes de información y/o consulta
                            y para
                            obtener una resolución de las mismas.</small>
                    </h2>
                </div>
                <div class="body">
                    <form method="POST" id="formulario">
                        {% csrf_token %}
                        <div class="row clearfix">
                            <input type="hidden" name="nombreUsuario" value="{{ user.nombreUsuario }}"
                                id="id_nombreUsuario">
                            <div class="col-md-2"></div>
                            <div class=" col-md-8">
                                <p>
                                    <b>Descripción</b>
                                </p>
                                <div class="form-group">
                                    <div class="form-line">
                                        {{ form.descripcion }}
                                        {{ form.descripcion.errors }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="categoria" id="id_categoria" class="form-control" value="P" required>
                        <div class="row clearfix">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <a href="{% url 'inicio_cliente' %}">
                                            <button type="button" class="btn bg-teal waves-effect">Atrás</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <button type="reset" class="btn bg-blue-grey waves-effect">Limpiar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <div class="button-demo">
                                        <button type="button" onclick="javascript:confirmarSeleccion();"
                                            class="btn bg-green waves-effect">Enviar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block javascript %}

{% if messages %}
{% for m in messages %}
{% if m.message == "e" %}
<script>
    swal("Enviada", "La petición ha sido enviada con éxito.", "success");
</script>
{% endif %}
{% endfor %}
{% endif %}
<script>
    function confirmarSeleccion() {
        swal({
            title: "Confirmar envío",
            text: "¿Está seguro que desea enviar la petición?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#58a05d",
            confirmButtonText: "Sí",
            cancelButtonText: "Cancelar",
            closeOnConfirm: false,
            closeOnCancel: false
        }, function (isConfirm) {
            if (isConfirm) {
                formulario.submit();
            } else {
                swal("Cancelada", "La petición no ha sido enviada.", "error");
            }
        });
    }
</script>

{% endblock %}